# app1-pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
    - name: app1
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=Hello, I'm app1"
        - "-listen=:80"

---
# App1 service

kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - port: 80