# app1-pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: app2
  labels:
    app: app2
spec:
  containers:
    - name: app2
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=Second app using Cilium"
        - "-listen=:8080"