apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment02
  labels:
    app: testApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Hello, I'm using Cilium"
          - "-listen=:80"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
    - port: 80